version: "3.8"

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dockerdeployer-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - db_data:/app/data
      - config_repo:/app/config_repo
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./data/dockerdeployer.db
      - JWT_SECRET_KEY=${SECRET_KEY:-dev_secret_key_change_in_production}
      - CONFIG_REPO_PATH=/app/config_repo
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dockerdeployer-frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db_data:
  config_repo:
