llm_api_key: ''
llm_api_url: ''
llm_provider: openrouter
openrouter_api_key: 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
openrouter_api_url: https://openrouter.ai/api/v1/chat/completions
secrets: {}
