name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        component: [backend, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python (for backend)
        if: matrix.component == 'backend'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js (for frontend)
        if: matrix.component == 'frontend'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Update Python dependencies
        if: matrix.component == 'backend'
        run: |
          cd backend
          pip install --upgrade pip pip-tools
          pip-compile --upgrade requirements.in || pip-compile --upgrade requirements.txt
          pip-compile --upgrade requirements-dev.in || pip-compile --upgrade requirements-dev.txt

      - name: Update Node.js dependencies
        if: matrix.component == 'frontend'
        run: |
          cd frontend
          npm update
          npm audit fix --audit-level moderate || true

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(${{ matrix.component }}): update dependencies"
          title: "chore(${{ matrix.component }}): Update dependencies"
          body: |
            ## 📦 Dependency Updates for ${{ matrix.component }}

            This PR updates dependencies for the ${{ matrix.component }} component.

            ### Changes
            - Updated dependencies to their latest compatible versions
            - Fixed security vulnerabilities (if any)

            ### Testing
            - [ ] All tests pass
            - [ ] No breaking changes detected
            - [ ] Security scan passes

            **Auto-generated by GitHub Actions**
          branch: dependency-updates/${{ matrix.component }}
          delete-branch: true
          labels: |
            dependencies
            ${{ matrix.component }}
            automated

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Python security audit
        run: |
          cd backend
          pip install safety
          safety check --json --output safety-report.json || true
          if [ -f safety-report.json ]; then
            echo "Python security issues found:"
            cat safety-report.json
          fi

      - name: Node.js security audit
        run: |
          cd frontend
          npm audit --audit-level moderate --json > npm-audit.json || true
          if [ -s npm-audit.json ]; then
            echo "Node.js security issues found:"
            cat npm-audit.json
          fi

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            backend/safety-report.json
            frontend/npm-audit.json
